version: "3.9"
services:
  project-name:
    image: postgres
    restart: always
    container_name: project-name
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
